name: Build and Deploy
on:
  push:
    branches:
      - main  # Set a branch to trigger deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: jekyll build  # Replace this with your build command

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Set this to your site's build directory
https://sub.7878787878.top/api/v1/client/subscribe?token=718ebd21132bff3d4d1f4d653aa1acde